export type CategoryLabel =
  | "INJECTION"
  | "ORAL"
  | "POST CYCLE"
  | "FAT BURN"
  | "SEXUAL WELLNESS"
  | "PEPTIDES & HGH"
  | "SARMS"
  | "AMINO ACIDS"
  | "ALL PRODUCTS";

export type Brand = "deus" | "astera";

export type Product = {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: CategoryLabel;
  brand: Brand;
  filterType?: string;
};

// Produktdatenbank
export const products: Product[] = [
  // INJECTION - DEUS
  {
    id: "inj-deus-001",
    name: "DEUS 3-TRENBOMED 150",
    description:
      "Trenbolone Enanthate 50mg, Trenbolone Acetate 50mg, Trenbolone Hexahydrobenzylcarbonate 50mg",
    price: 45.0,
    image: "/products/deus inject/DEUS 3-TRENBOMED 150.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Definition",
  },
  {
    id: "inj-deus-002",
    name: "DEUS EQUIMED 250",
    description: "Boldenone Undecylenate 250mg",
    price: 38.0,
    image: "/products/deus inject/DEUS EQUIMED 250.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "inj-deus-003",
    name: "DEUS DECAMED 250",
    description: "Nandrolone Decanoate 250mg",
    price: 38.0,
    image: "/products/deus inject/DEUS DECAMED 250.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "inj-deus-004",
    name: "DEUS DECAMED PP 100",
    description: "Nandrolone Phenylpropionate 100mg",
    price: 31.0,
    image: "/products/deus inject/DEUS DECAMED PP 100.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "inj-deus-005",
    name: "DEUS DHB-MED 100",
    description: "Dihydroboldenone Cypionate 100mg",
    price: 50.0,
    image: "/products/deus inject/DEUS DHB-MED 100.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Definition",
  },
  {
    id: "inj-deus-006",
    name: "DEUS DIANAMED 100",
    description: "Methandienone 100mg",
    price: 36.0,
    image: "/products/deus inject/DEUS DIANAMED 100.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "inj-deus-007",
    name: "DEUS TESTOMED C 250",
    description: "Testosterone Cypionate 250mg",
    price: 30.0,
    image: "/products/deus inject/DEUS TESTOMED C 250.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "inj-deus-008",
    name: "DEUS TESTOMED E 250",
    description: "Testosterone Enanthate 250mg",
    price: 30.0,
    image: "/products/deus inject/DEUS TESTOMED E 250.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "inj-deus-009",
    name: "DEUS MASTERMED E 200",
    description: "Drostanolone Enanthate 200mg",
    price: 50.0,
    image: "/products/deus inject/DEUS MASTERMED E 200.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Definition",
  },
  {
    id: "inj-deus-010",
    name: "DEUS MASTERMED P 100",
    description: "Drostanolone Propionate 100mg",
    price: 40.0,
    image: "/products/deus inject/DEUS MASTERMED P 100.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Definition",
  },
  {
    id: "inj-deus-011",
    name: "DEUS PARAMED 76.5",
    description: "Trenbolone Hexahydrobenzylcarbonate 76.5mg",
    price: 50.0,
    image: "/products/deus inject/DEUS PARAMED 76.5.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Definition",
  },
  {
    id: "inj-deus-012",
    name: "DEUS PRIMOMED 100",
    description: "Methenolone Enanthate 100mg",
    price: 59.0,
    image: "/products/deus inject/DEUS PRIMOMED 100.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Definition",
  },
  {
    id: "inj-deus-013",
    name: "DEUS SUSTAMED 250",
    description:
      "Testosterone Phenylpropionate 60mg, Testosterone Isocaproate 60mg, Testosterone Decanoate 100mg, Testosterone Propionate 30mg",
    price: 32.0,
    image: "/products/deus inject/DEUS SUSTAMED 250.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "inj-deus-014",
    name: "DEUS TESTOMED 100",
    description: "Testosterone Base 100mg",
    price: 28.0,
    image: "/products/deus inject/DEUS TESTOMED 100.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "inj-deus-015",
    name: "DEUS TESTOMED P 100",
    description: "Testosterone Propionate 100mg",
    price: 26.0,
    image: "/products/deus inject/DEUS TESTOMED P 100.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "inj-deus-016",
    name: "DEUS TESTOMED PP 100",
    description: "Testosterone Phenylpropionate 100mg",
    price: 26.0,
    image: "/products/deus inject/DEUS TESTOMED PP 100.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "inj-deus-017",
    name: "DEUS TESTOMED U 250",
    description: "Testosterone Undecanoate 250mg",
    price: 30.0,
    image: "/products/deus inject/DEUS TESTOMED U 250.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "inj-deus-018",
    name: "DEUS TRENBOMED A 100",
    description: "Trenbolone Acetate 100mg",
    price: 41.0,
    image: "/products/deus inject/DEUS TRENBOMED A 100.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Definition",
  },
  {
    id: "inj-deus-019",
    name: "DEUS TRENBOMED E 200",
    description: "Trenbolone Enanthate 200mg",
    price: 50.0,
    image: "/products/deus inject/DEUS TRENBOMED E 200.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Definition",
  },
  {
    id: "inj-deus-020",
    name: "DEUS TRESTOLONE A 100",
    description: "Trestolone Acetate 100mg",
    price: 100.0,
    image: "/products/deus inject/DEUS TRESTOLONE A 100.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "inj-deus-021",
    name: "DEUS TRESTOLONE E 100",
    description: "Trestolone Enanthate 100mg",
    price: 100.0,
    image: "/products/deus inject/DEUS TRESTOLONE E 100.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "inj-deus-022",
    name: "DEUS WINIMED 50",
    description: "Stanozolol 50mg",
    price: 33.0,
    image: "/products/deus inject/DEUS WINIMED 50.png",
    category: "INJECTION",
    brand: "deus",
    filterType: "Definition",
  },

  // INJECTION - ASTERA
  {
    id: "inj-astera-001",
    name: "ASTERA BACTERIOSTATIC WATER",
    description: "Bacteriostatic Water 10 ml",
    price: 10.0,
    image: "/products/astera inject/ASTERA BACTERIOSTATIC WATER.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "inj-astera-002",
    name: "ASTERA BOLDENONE ACETATE 50",
    description: "Boldenone Acetate 50mg",
    price: 35.0,
    image: "/products/astera inject/ASTERA BOLDENONE ACETATE 50.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-003",
    name: "ASTERA BOLDENONE CYPIONATE 200",
    description: "Boldenone cypionate 200 mg",
    price: 40.0,
    image: "/products/astera inject/ASTERA BOLDENONE CYPIONATE 200.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-004",
    name: "ASTERA BOLDENONE UNDECYLENATE 300",
    description: "Boldenone Undecylenate 300 mg",
    price: 43.0,
    image: "/products/astera inject/ASTERA BOLDENONE UNDECYLENATE 300.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-005",
    name: "ASTERA DIHYDROBOLDENONE 100",
    description: "Dihydroboldenone (DHB) 100mg",
    price: 50.0,
    image: "/products/astera inject/ASTERA DIHYDROBOLDENONE 100.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-006",
    name: "ASTERA DROSTANOLONE ENANTHATE 200",
    description: "Drostanolone Enanthate 200mg",
    price: 50.0,
    image: "/products/astera inject/ASTERA DROSTANOLONE ENANTHATE 200.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Definition",
  },
  {
    id: "inj-astera-007",
    name: "ASTERA DROSTANOLONE PROPIONATE 100",
    description: "Drostanolone Propionate 100mg",
    price: 40.0,
    image: "/products/astera inject/ASTERA DROSTANOLONE PROPIONATE 100.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Definition",
  },
  {
    id: "inj-astera-008",
    name: "ASTERA LGD-4033 60",
    description: "Ligandrol 60mg",
    price: 50.0,
    image: "/products/astera inject/ASTERA LGD-4033 60.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-009",
    name: "ASTERA LONG ACTING MIX 500",
    description:
      "Drostanolone Enanthate 200mg, Testosterone Enanthate 200mg, Trenbolone Enanthate 100mg",
    price: 90.0,
    image: "/products/astera inject/ASTERA LONG ACTING MIX 500.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Definition",
  },
  {
    id: "inj-astera-010",
    name: "ASTERA METHANDIENONE 100",
    description: "Methandienone 100mg",
    price: 36.0,
    image: "/products/astera inject/ASTERA METHANDIENONE 100.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-011",
    name: "ASTERA METHENOLONE ENANTHATE 100",
    description: "Methenolone Enanthate 100mg",
    price: 59.0,
    image: "/products/astera inject/ASTERA METHENOLONE ENANTHATE 100.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-012",
    name: "ASTERA METHENOLONE ENANTHATE 200",
    description: "Methenolone Enanthate 200mg",
    price: 110.0,
    image: "/products/astera inject/ASTERA METHENOLONE ENANTHATE 200.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-013",
    name: "ASTERA METHYLDROSTANOLONE 40",
    description: "Methyldrostanolone (Superdrol) 40mg",
    price: 40.0,
    image: "/products/astera inject/ASTERA METHYLDROSTANOLONE 40.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-014",
    name: "ASTERA NANDROLONE DECANOATE 300",
    description: "Nandrolone Decanoate 300mg",
    price: 45.0,
    image: "/products/astera inject/ASTERA NANDROLONE DECANOATE 300.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-015",
    name: "ASTERA NANDROLONE PHENYLPROPIONATE 100",
    description: "Nandrolone phenylpropionate (NPP) 100mg",
    price: 30.0,
    image: "/products/astera inject/ASTERA NANDROLONE PHENYLPROPIONATE 100.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-016",
    name: "ASTERA OXYMETHOLONE 50",
    description: "Oxymetholone 50mg",
    price: 25.0,
    image: "/products/astera inject/ASTERA OXYMETHOLONE 50.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-017",
    name: "ASTERA SHORT ACTING MIX 275",
    description:
      "Drostanolone propionate 75mg, Testosterone propionate 125mg, Trenbolone acetate 75mg",
    price: 80.0,
    image: "/products/astera inject/ASTERA SHORT ACTING MIX 275.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Definition",
  },
  {
    id: "inj-astera-018",
    name: "ASTERA STANOZOLOL 50",
    description: "Stanozolol 50mg",
    price: 32.0,
    image: "/products/astera inject/ASTERA STANOZOLOL 50.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Definition",
  },
  {
    id: "inj-astera-019",
    name: "ASTERA STENBOLONE 100",
    description: "Stenbolone Acetate 100mg",
    price: 50.0,
    image: "/products/astera inject/ASTERA STENBOLONE 100.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-020",
    name: "ASTERA SUSTANON 300",
    description:
      "Testosterone Decanoate 120mg, Testosterone Isocaproate 72mg, Testosterone Phenylpropionate 72mg, Testosterone Propionate 36mg",
    price: 38.0,
    image: "/products/astera inject/ASTERA SUSTANON 300.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-021",
    name: "ASTERA SUSTANON 500",
    description:
      "Testosterone Decanoate 200mg, Testosterone Isocaproate 120mg, Testosterone Phenylpropionate 120mg, Testosterone Propionate 60mg",
    price: 60.0,
    image: "/products/astera inject/ASTERA SUSTANON 500.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-022",
    name: "ASTERA TESTOSTERONE CYPIONATE 200",
    description: "Testosterone Cypionate 200mg",
    price: 24.0,
    image: "/products/astera inject/ASTERA TESTOSTERONE CYPIONATE 200.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-023",
    name: "ASTERA TESTOSTERONE ENANTHATE 300",
    description: "Testosterone Enanthate 300mg",
    price: 35.0,
    image: "/products/astera inject/ASTERA TESTOSTERONE ENANTHATE 300.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-024",
    name: "ASTERA TESTOSTERONE NO ESTER 100",
    description: "Testosterone Base 100mg",
    price: 28.0,
    image: "/products/astera inject/ASTERA TESTOSTERONE NO ESTER 100.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "inj-astera-025",
    name: "ASTERA TESTOSTERONE PHENYLPROPIONATE 100",
    description: "Testosterone Phenylpropionate 100mg",
    price: 26.0,
    image:
      "/products/astera inject/ASTERA TESTOSTERONE PHENYLPROPIONATE 100.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-026",
    name: "ASTERA TESTOSTERONE PROPIONATE 100",
    description: "Testosterone Propionate 100mg",
    price: 26.0,
    image: "/products/astera inject/ASTERA TESTOSTERONE PROPIONATE 100.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-027",
    name: "ASTERA TESTOSTERONE UNDECANOATE 250",
    description: "Testosterone Undecanoate 250mg",
    price: 30.0,
    image: "/products/astera inject/ASTERA TESTOSTERONE UNDECANOATE 250.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-028",
    name: "ASTERA TRENBOLONE ACETATE 100",
    description: "Trenbolone Acetate 100mg",
    price: 41.0,
    image: "/products/astera inject/ASTERA TRENBOLONE ACETATE 100.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Definition",
  },
  {
    id: "inj-astera-029",
    name: "ASTERA TRENBOLONE BASE 50",
    description: "Trenbolone Base 50mg",
    price: 35.0,
    image: "/products/astera inject/ASTERA TRENBOLONE BASE 50.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "inj-astera-030",
    name: "ASTERA TRENBOLONE ENANTHATE 200",
    description: "Trenbolone Enanthate 200mg",
    price: 50.0,
    image: "/products/astera inject/ASTERA TRENBOLONE ENANTHATE 200.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-031",
    name: "ASTERA TRENBOLONE HEXAHYDROBENZYL CARBONATE 100",
    description: "Trenbolone Hexahydrobenzylcarbonate 100mg",
    price: 60.0,
    image:
      "/products/astera inject/ASTERA TRENBOLONE HEXAHYDROBENZYL CARBONATE 100.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-032",
    name: "ASTERA TRENBOLONE MIX 150",
    description:
      "Trenbolone Acetate 50mg, Trenbolone Enanthate 50mg, Trenbolone Hexahydrobenzylcarbonate 50mg",
    price: 45.0,
    image: "/products/astera inject/ASTERA TRENBOLONE MIX 150.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-033",
    name: "ASTERA TRESTOLONE ACETATE 50",
    description: "Trestolone Acetate 50mg",
    price: 55.0,
    image: "/products/astera inject/ASTERA TRESTOLONE ACETATE 50.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "inj-astera-034",
    name: "ASTERA TRESTOLONE ENANTHATE 50",
    description: "Trestolone Enanthate 50mg",
    price: 55.0,
    image: "/products/astera inject/ASTERA TRESTOLONE ENANTHATE 50.png",
    category: "INJECTION",
    brand: "astera",
    filterType: "Gain",
  },

  // ORAL - DEUS
  {
    id: "oral-deus-001",
    name: "DEUS ANADROMED 50",
    description: "Oxymetholone 50mg",
    price: 27.0,
    image: "/products/deus oral/DEUS ANADROMED 50.png",
    category: "ORAL",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "oral-deus-002",
    name: "DEUS ANAVAMED 10",
    description: "Oxandrolone 10mg",
    price: 23.0,
    image: "/products/deus oral/DEUS ANAVAMED 10.png",
    category: "ORAL",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "oral-deus-003",
    name: "DEUS DIANAMED 10",
    description: "Methandienone 10mg",
    price: 10.0,
    image: "/products/deus oral/DEUS DIANAMED 10.png",
    category: "ORAL",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "oral-deus-004",
    name: "DEUS HALOMED 5",
    description: "Fluoxymesterone 5mg",
    price: 45.0,
    image: "/products/deus oral/DEUS HALOMED 5.png",
    category: "ORAL",
    brand: "deus",
    filterType: "Definition",
  },
  {
    id: "oral-deus-005",
    name: "DEUS PRIMOMED 25",
    description: "Methenolone Acetate 25mg",
    price: 75.0,
    image: "/products/deus oral/DEUS PRIMOMED 25.png",
    category: "ORAL",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "oral-deus-006",
    name: "DEUS PROVIMED 25",
    description: "Mesterolone 25mg",
    price: 23.0,
    image: "/products/deus oral/DEUS PROVIMED 25.png",
    category: "ORAL",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "oral-deus-007",
    name: "DEUS SUPERMED 10",
    description: "Methyldrostanolone 10mg",
    price: 41.0,
    image: "/products/deus oral/DEUS SUPERMED 10.png",
    category: "ORAL",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "oral-deus-008",
    name: "DEUS TURIMED 10",
    description: "4-Chlorodehydromethyltestosterone 10mg",
    price: 17.0,
    image: "/products/deus oral/DEUS TURIMED 10.png",
    category: "ORAL",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "oral-deus-009",
    name: "DEUS WINIMED 10",
    description: "Stanozolol 10mg",
    price: 11.0,
    image: "/products/deus oral/DEUS WINIMED 10.png",
    category: "ORAL",
    brand: "deus",
    filterType: "Definition",
  },

  // ORAL - ASTERA
  {
    id: "oral-astera-001",
    name: "ASTERA CHLORODEHYDROMETHYL TESTOSTERONE 20",
    description: "Chlorodehydromethyltestosterone 20mg",
    price: 65.0,
    image:
      "/products/astera oral/ASTERA CHLORODEHYDROMETHYL TESTOSTERONE 20.png",
    category: "ORAL",
    brand: "astera",
    filterType: "Definition",
  },
  {
    id: "oral-astera-002",
    name: "ASTERA FLUOXYMESTERONE 5",
    description: "Fluoxymesterone (Halotestin) 5mg",
    price: 45.0,
    image: "/products/astera oral/ASTERA FLUOXYMESTERONE 5.png",
    category: "ORAL",
    brand: "astera",
    filterType: "Definition",
  },
  {
    id: "oral-astera-003",
    name: "ASTERA MESTEROLONE 50",
    description: "Mesterolone 50mg",
    price: 60.0,
    image: "/products/astera oral/ASTERA MESTEROLONE 50.png",
    category: "ORAL",
    brand: "astera",
    filterType: "Definition",
  },
  {
    id: "oral-astera-004",
    name: "ASTERA METHANDIENONE 20",
    description: "Methadienone 20mg",
    price: 40.0,
    image: "/products/astera oral/ASTERA METHANDIENONE 20.png",
    category: "ORAL",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "oral-astera-005",
    name: "ASTERA METHYL-1-TESTOSTERONE 10",
    description: "Methyl-1-testosterone 10mg",
    price: 30.0,
    image: "/products/astera oral/ASTERA METHYL-1-TESTOSTERONE 10.png",
    category: "ORAL",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "oral-astera-006",
    name: "ASTERA METHYLDROSTANOLONE 10",
    description: "Methyldrostanolone (Superdrol) 10mg",
    price: 41.0,
    image: "/products/astera oral/ASTERA METHYLDROSTANOLONE 10.png",
    category: "ORAL",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "oral-astera-007",
    name: "ASTERA METHYLTESTOSTERONE 25",
    description: "Methyldrostanolone 25mg",
    price: 35.0,
    image: "/products/astera oral/ASTERA METHYLTESTOSTERONE 25.png",
    category: "ORAL",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "oral-astera-008",
    name: "ASTERA METHYLTRENBOLONE 1",
    description: "Methyltrenbolone 1mg",
    price: 45.0,
    image: "/products/astera oral/ASTERA METHYLTRENBOLONE 1.png",
    category: "ORAL",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "oral-astera-009",
    name: "ASTERA MIBOLERONE 0.5",
    description: "Mibolerone 0.5mg",
    price: 60.0,
    image: "/products/astera oral/ASTERA MIBOLERONE 0.5.png",
    category: "ORAL",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "oral-astera-010",
    name: "ASTERA OXANDROLONE 20",
    description: "Oxandrolone 20mg",
    price: 90.0,
    image: "/products/astera oral/ASTERA OXANDROLONE 20.png",
    category: "ORAL",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "oral-astera-011",
    name: "ASTERA OXYMETHOLONE 25",
    description: "Oxymetholone 25mg",
    price: 30.0,
    image: "/products/astera oral/ASTERA OXYMETHOLONE 25.png",
    category: "ORAL",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "oral-astera-012",
    name: "ASTERA STANOZOLOL 20",
    description: "Stanozolol 20mg",
    price: 44.0,
    image: "/products/astera oral/ASTERA STANOZOLOL 20.png",
    category: "ORAL",
    brand: "astera",
    filterType: "Definition",
  },

  // SARMS - DEUS (9 Produkte)
  {
    id: "sarms-deus-001",
    name: "DEUS GW501516 10 CARDARINE",
    description: "Cardarine 10mg",
    price: 35.0,
    image: "/products/deus sarms/DEUS GW501516 10 CARDARINE.png",
    category: "SARMS",
    brand: "deus",
    filterType: "Allround",
  },
  {
    id: "sarms-deus-002",
    name: "DEUS LGD4033 10 LIGANDROL",
    description: "Ligandrol 10mg",
    price: 60.0,
    image: "/products/deus sarms/DEUS LGD4033 10 LIGANDROL.png",
    category: "SARMS",
    brand: "deus",
    filterType: "Allround",
  },
  {
    id: "sarms-deus-003",
    name: "DEUS MK677 10 IBUTAMOREN",
    description: "Ibutamoren 10mg",
    price: 40.0,
    image: "/products/deus sarms/DEUS MK677 10 IBUTAMOREN.png",
    category: "SARMS",
    brand: "deus",
    filterType: "Allround",
  },
  {
    id: "sarms-deus-004",
    name: "DEUS MK2866 10 OSTARINE",
    description: "Ostarine 10mg",
    price: 33.0,
    image: "/products/deus sarms/DEUS MK2866 10 OSTARINE.png",
    category: "SARMS",
    brand: "deus",
    filterType: "Allround",
  },
  {
    id: "sarms-deus-005",
    name: "DEUS RAD140 10 TESTOLONE",
    description: "Testolone 10mg",
    price: 50.0,
    image: "/products/deus sarms/DEUS RAD140 10 TESTOLONE.png",
    category: "SARMS",
    brand: "deus",
    filterType: "Allround",
  },
  {
    id: "sarms-deus-006",
    name: "DEUS S4 25 ANDARINE",
    description: "Andarine 25mg",
    price: 45.0,
    image: "/products/deus sarms/DEUS S4 25 ANDARINE.png",
    category: "SARMS",
    brand: "deus",
    filterType: "Allround",
  },
  {
    id: "sarms-deus-007",
    name: "DEUS S23 10",
    description: "S23 10mg",
    price: 35.0,
    image: "/products/deus sarms/DEUS S23 10.png",
    category: "SARMS",
    brand: "deus",
    filterType: "Allround",
  },
  {
    id: "sarms-deus-008",
    name: "DEUS SR9009 10 STENABOLIC",
    description: "Stenabolic 10mg",
    price: 35.0,
    image: "/products/deus sarms/DEUS SR9009 10 STENABOLIC.png",
    category: "SARMS",
    brand: "deus",
    filterType: "Allround",
  },
  {
    id: "sarms-deus-009",
    name: "DEUS YK11 5",
    description: "YK11 5mg",
    price: 55.0,
    image: "/products/deus sarms/DEUS YK11 5.png",
    category: "SARMS",
    brand: "deus",
    filterType: "Allround",
  },

  // SARMS - ASTERA
  {
    id: "sarms-astera-001",
    name: "ASTERA GW501516 10",
    description: "GW501516 Cardarine 10mg",
    price: 35.0,
    image: "/products/astera sarms/ASTERA GW501516 10.png",
    category: "SARMS",
    brand: "astera",
    filterType: "Definition",
  },
  {
    id: "sarms-astera-002",
    name: "ASTERA LGD4033 10",
    description: "LGD4033 Ligandrol 10mg",
    price: 35.0,
    image: "/products/astera sarms/ASTERA LGD4033 10.png",
    category: "SARMS",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "sarms-astera-003",
    name: "ASTERA MK2866 10",
    description: "MK-2866 Ostarine 10mg",
    price: 30.0,
    image: "/products/astera sarms/ASTERA MK2866 10.png",
    category: "SARMS",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "sarms-astera-004",
    name: "ASTERA MK677 10",
    description: "MK-677 Ibutamoren 10mg",
    price: 35.0,
    image: "/products/astera sarms/ASTERA MK677 10.png",
    category: "SARMS",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "sarms-astera-005",
    name: "ASTERA RAD140 10",
    description: "RAD140 Testolone 10mg",
    price: 45.0,
    image: "/products/astera sarms/ASTERA RAD140 10.png",
    category: "SARMS",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "sarms-astera-006",
    name: "ASTERA S23 10",
    description: "S23 10mg",
    price: 30.0,
    image: "/products/astera sarms/ASTERA S23 10.png",
    category: "SARMS",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "sarms-astera-007",
    name: "ASTERA S4 25",
    description: "S4 Andarine 25mg",
    price: 35.0,
    image: "/products/astera sarms/ASTERA S4 25.png",
    category: "SARMS",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "sarms-astera-008",
    name: "ASTERA SR9009 10",
    description: "SR9009 Stenabolic 10mg",
    price: 35.0,
    image: "/products/astera sarms/ASTERA SR9009 10.png",
    category: "SARMS",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "sarms-astera-009",
    name: "ASTERA YK11 5",
    description: "YK11 5mg",
    price: 40.0,
    image: "/products/astera sarms/ASTERA YK11 5.png",
    category: "SARMS",
    brand: "astera",
    filterType: "Gain",
  },

  // PEPTIDES & HGH - DEUS
  {
    id: "peptides-deus-001",
    name: "DEUS BPC-157",
    description: "BPC-157 Pentadecapeptide 5mg",
    price: 35.0,
    image: "/products/deus peptides & hgh/DEUS BPC-157.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "peptides-deus-002",
    name: "DEUS CJC-1295 DAC",
    description: "Tetrasubstitued 30-Amino Acid Peptide Hormone 2mg",
    price: 30.0,
    image: "/products/deus peptides & hgh/DEUS CJC-1295 DAC.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "peptides-deus-003",
    name: "DEUS DEUSTROPIN 4/12",
    description: "Recombinant Human Growth Hormone [rDNA origin] 12IU",
    price: 190.0,
    image: "/products/deus peptides & hgh/DEUS DEUSTROPIN 4:12.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "peptides-deus-004",
    name: "DEUS DSIP",
    description: "Delta Sleep-Inducing Peptide 5mg",
    price: 35.0,
    image: "/products/deus peptides & hgh/DEUS DSIP.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "peptides-deus-005",
    name: "DEUS EPITHALON",
    description: "Epithalamine 10mg",
    price: 30.0,
    image: "/products/deus peptides & hgh/DEUS EPITHALON.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "peptides-deus-006",
    name: "DEUS EPO",
    description: "Erythropoietin 3000IU",
    price: 0.0,
    image: "/products/deus peptides & hgh/DEUS EPO.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "peptides-deus-007",
    name: "DEUS FOLLISTATIN",
    description: "Activin-Binding Protein 1mg",
    price: 60.0,
    image: "/products/deus peptides & hgh/DEUS FOLLISTATIN.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "peptides-deus-008",
    name: "DEUS GHRP-2",
    description: "Growth Hormone-Releasing Peptide 2 10mg",
    price: 35.0,
    image: "/products/deus peptides & hgh/DEUS GHRP-2.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "peptides-deus-009",
    name: "DEUS GHRP-6",
    description: "Growth Hormone-Releasing Peptide 6 10mg",
    price: 35.0,
    image: "/products/deus peptides & hgh/DEUS GHRP-6.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "peptides-deus-010",
    name: "DEUS HCG",
    description: "Human Chorionic Gonadotropin 5000IU",
    price: 40.0,
    image: "/products/deus peptides & hgh/DEUS HCG.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "peptides-deus-011",
    name: "DEUS HEXARELIN",
    description: "Growth Hormone-Releasing Peptide 2mg",
    price: 30.0,
    image: "/products/deus peptides & hgh/DEUS HEXARELIN.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "peptides-deus-012",
    name: "DEUS HGH FRAGMENT 176-191",
    description: "Recombinant Human Growth Hormone Fragment 176-191 5mg",
    price: 40.0,
    image: "/products/deus peptides & hgh/DEUS HGH FRAGMENT 176-191.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Definition",
  },
  {
    id: "peptides-deus-013",
    name: "DEUS HMG",
    description: "Human Menopausal Gonadotropin 0.15mg",
    price: 40.0,
    image: "/products/deus peptides & hgh/DEUS HMG.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "peptides-deus-014",
    name: "DEUS IGF-1 DES",
    description: "Insulin-Like Growth Factor 1 DES 1mg",
    price: 0.0,
    image: "/products/deus peptides & hgh/DEUS IGF-1 DES.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "peptides-deus-015",
    name: "DEUS IGF-1 LR3",
    description: "Long Arginine 3-IGF-1 1mg",
    price: 0.0,
    image: "/products/deus peptides & hgh/DEUS IGF-1 LR3.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "peptides-deus-016",
    name: "DEUS IPAMORELIN",
    description: "Growth Hormone-Releasing Peptide 2mg",
    price: 20.0,
    image: "/products/deus peptides & hgh/DEUS IPAMORELIN.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "peptides-deus-017",
    name: "DEUS MELANOTAN II",
    description: "Melanotan II Peptide Hormone 10mg",
    price: 30.0,
    image: "/products/deus peptides & hgh/DEUS MELANOTAN II.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "peptides-deus-018",
    name: "DEUS MOD GRF 1-29",
    description: "Tetrasubstitued 29-Amino Acid Peptide Hormone 2mg",
    price: 20.0,
    image: "/products/deus peptides & hgh/DEUS MOD GRF 1-29.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "peptides-deus-019",
    name: "DEUS MOTS-C",
    description: "Mitochondrial-Derived Peptide 10mg",
    price: 50.0,
    image: "/products/deus peptides & hgh/DEUS MOTS-C.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "peptides-deus-020",
    name: "DEUS PEG MGF",
    description: "Pegylated Mechano Growth Factor 2mg",
    price: 33.0,
    image: "/products/deus peptides & hgh/DEUS PEG MGF.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Gain",
  },
  {
    id: "peptides-deus-021",
    name: "DEUS PNC-27",
    description: "PNC-27 Anti-Cancer Peptide 5mg",
    price: 50.0,
    image: "/products/deus peptides & hgh/DEUS PNC-27.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "peptides-deus-022",
    name: "DEUS PT-141",
    description: "Bremelanotide 10mg",
    price: 30.0,
    image: "/products/deus peptides & hgh/DEUS PT-141.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "peptides-deus-023",
    name: "DEUS SELANK",
    description: "Seelank Anxiolytic Peptide 5mg",
    price: 15.0,
    image: "/products/deus peptides & hgh/DEUS SELANK.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "peptides-deus-024",
    name: "DEUS SEMAGLUTIDE",
    description: "Glucagon-Like Peptide-1 GLP-1 5mg",
    price: 100.0,
    image: "/products/deus peptides & hgh/DEUS SEMAGLUTIDE.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Definition",
  },
  {
    id: "peptides-deus-025",
    name: "DEUS SEMAX",
    description: "Semax Heptapeptide 5mg",
    price: 15.0,
    image: "/products/deus peptides & hgh/DEUS SEMAX.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "peptides-deus-026",
    name: "DEUS TB-500",
    description: "Thymosin Beta-4 2mg",
    price: 30.0,
    image: "/products/deus peptides & hgh/DEUS TB-500.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "peptides-deus-027",
    name: "DEUS THYMOSIN A1",
    description: "Thymic Factor 10mg",
    price: 60.0,
    image: "/products/deus peptides & hgh/DEUS THYMOSIN A1.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "peptides-deus-028",
    name: "DEUS TIRZEPATIDE",
    description: "GIP and GLP-1 Receptor agonist 10mg",
    price: 100.0,
    image: "/products/deus peptides & hgh/DEUS TIRZEPATIDE.png",
    category: "PEPTIDES & HGH",
    brand: "deus",
    filterType: "Definition",
  },

  // PEPTIDES & HGH - ASTERA
  {
    id: "peptides-astera-001",
    name: "ASTERA HCG 5000",
    description: "Human Chorionic Gonadotropin (HCG), 5000 IU",
    price: 40.0,
    image: "/products/astera peptides & hgh/ASTERA HCG 5000.png",
    category: "PEPTIDES & HGH",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "peptides-astera-002",
    name: "ASTERA HGH 16",
    description: "Human Growth Hormone (HGH), 16 IU",
    price: 250.0,
    image: "/products/astera peptides & hgh/ASTERA HGH 16.png",
    category: "PEPTIDES & HGH",
    brand: "astera",
    filterType: "Gain",
  },
  {
    id: "peptides-astera-003",
    name: "ASTERA HGH FRAGMENT 176-191 10",
    description: "HGH Fragment 176-191, 10 mg",
    price: 70.0,
    image: "/products/astera peptides & hgh/ASTERA HGH FRAGMENT 176-191 10.png",
    category: "PEPTIDES & HGH",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "peptides-astera-004",
    name: "ASTERA MELANOTAN 2 10",
    description: "Melanotan II Peptide Hormone, 10 mg",
    price: 30.0,
    image: "/products/astera peptides & hgh/ASTERA MELANOTAN 2 10.png",
    category: "PEPTIDES & HGH",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "peptides-astera-005",
    name: "ASTERA TB500 & BPC157 10",
    description: "TB500, BPC157 10 mg",
    price: 100.0,
    image: "/products/astera peptides & hgh/ASTERA TB500 & BPC157 10.png",
    category: "PEPTIDES & HGH",
    brand: "astera",
    filterType: "Base",
  },

  // FAT BURN - DEUS
  {
    id: "fatburn-deus-001",
    name: "DEUS CLENOMED 40",
    description: "Clenbuterol HCL 40mcg",
    price: 11.0,
    image: "/products/deus fat burn/DEUS CLENOMED 40.png",
    category: "FAT BURN",
    brand: "deus",
    filterType: "Definition",
  },
  {
    id: "fatburn-deus-002",
    name: "DEUS CYTOMED 25",
    description: "Liothyronine Sodium T3",
    price: 12.0,
    image: "/products/deus fat burn/DEUS CYTOMED 25.png",
    category: "FAT BURN",
    brand: "deus",
    filterType: "Definition",
  },
  {
    id: "fatburn-deus-003",
    name: "DEUS THYROMED 50",
    description: "Levothyroxine Sodium T4",
    price: 9.0,
    image: "/products/deus fat burn/DEUS THYROMED 50.png",
    category: "FAT BURN",
    brand: "deus",
    filterType: "Definition",
  },

  // FAT BURN - ASTERA
  {
    id: "fatburn-astera-001",
    name: "ASTERA LEVOTHYROXINE SODIUM 50",
    description: "Levothyroxine Sodium 50mg",
    price: 9.0,
    image: "/products/astera fat burn/ASTERA LEVOTHYROXINE SODIUM 50.png",
    category: "FAT BURN",
    brand: "astera",
    filterType: "Definition",
  },
  {
    id: "fatburn-astera-002",
    name: "ASTERA LIOTHYRONINE SODIUM 25",
    description: "Liothyronine Sodium 25mg",
    price: 12.0,
    image: "/products/astera fat burn/ASTERA LIOTHYRONINE SODIUM 25.png",
    category: "FAT BURN",
    brand: "astera",
    filterType: "Definition",
  },
  {
    id: "fatburn-astera-003",
    name: "ASTERA CLENBUTEROL HCL 40",
    description: "Clenbuterol HCL 40mg",
    price: 22.0,
    image: "/products/astera fat burn/ASTERA CLENBUTEROL HCL 40.png",
    category: "FAT BURN",
    brand: "astera",
    filterType: "Definition",
  },

  // POST CYCLE - DEUS
  {
    id: "pct-deus-001",
    name: "DEUS ARIMIMED 1",
    description: "Anastrozole 1mg",
    price: 27.0,
    image: "/products/deus post cycle/DEUS ARIMIMED 1.png",
    category: "POST CYCLE",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "pct-deus-002",
    name: "DEUS AROMAMED 25",
    description: "Exemestane 25mg",
    price: 30.0,
    image: "/products/deus post cycle/DEUS AROMAMED 25.png",
    category: "POST CYCLE",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "pct-deus-003",
    name: "DEUS CABERMED 0.5",
    description: "Cabergoline 0.5mg",
    price: 60.0,
    image: "/products/deus post cycle/DEUS CABERMED 0.5.png",
    category: "POST CYCLE",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "pct-deus-004",
    name: "DEUS CLOMIMED 50",
    description: "Clomiphene Citrate 50mg",
    price: 21.0,
    image: "/products/deus post cycle/DEUS CLOMIMED 50.png",
    category: "POST CYCLE",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "pct-deus-005",
    name: "DEUS ENCLOMIMED 25",
    description: "Enclomiphene Citrate 25mg",
    price: 60.0,
    image: "/products/deus post cycle/DEUS ENCLOMIMED 25.png",
    category: "POST CYCLE",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "pct-deus-006",
    name: "DEUS EVIMED 60",
    description: "Raloxifene 60mg",
    price: 25.0,
    image: "/products/deus post cycle/DEUS EVIMED 60.png",
    category: "POST CYCLE",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "pct-deus-007",
    name: "DEUS FEMAMED 2.5",
    description: "Letrozole 2.5mg",
    price: 35.0,
    image: "/products/deus post cycle/DEUS FEMAMED 2.5.png",
    category: "POST CYCLE",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "pct-deus-008",
    name: "DEUS NOLVAMED 20",
    description: "Tamoxifen Citrate 20mg",
    price: 23.0,
    image: "/products/deus post cycle/DEUS NOLVAMED 20.png",
    category: "POST CYCLE",
    brand: "deus",
    filterType: "Base",
  },

  // POST CYCLE - ASTERA
  {
    id: "pct-astera-001",
    name: "ASTERA ANASTROZOLE 1",
    description: "Anastrozole 1mg/tab",
    price: 27.0,
    image: "/products/astera post cycle/ASTERA ANASTROZOLE 1.png",
    category: "POST CYCLE",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "pct-astera-002",
    name: "ASTERA CABERGOLINE 0.25",
    description: "Cabergoline 0.25mg",
    price: 80.0,
    image: "/products/astera post cycle/ASTERA CABERGOLINE 0.25.png",
    category: "POST CYCLE",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "pct-astera-003",
    name: "ASTERA CLOMIPHENE CITRATE 50",
    description: "Clomiphene Citrate 50mg",
    price: 25.0,
    image: "/products/astera post cycle/ASTERA CLOMIPHENE CITRATE 50.png",
    category: "POST CYCLE",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "pct-astera-004",
    name: "ASTERA EXEMESTANE 25",
    description: "Exemestane 25mg",
    price: 55.0,
    image: "/products/astera post cycle/ASTERA EXEMESTANE 25.png",
    category: "POST CYCLE",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "pct-astera-005",
    name: "ASTERA LETROZOLE 1",
    description: "Letrozole 1mg",
    price: 13.0,
    image: "/products/astera post cycle/ASTERA LETROZOLE 1.png",
    category: "POST CYCLE",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "pct-astera-006",
    name: "ASTERA TAMOXIFEN 20",
    description: "Tamoxifen 20mg",
    price: 22.0,
    image: "/products/astera post cycle/ASTERA TAMOXIFEN 20.png",
    category: "POST CYCLE",
    brand: "astera",
    filterType: "Base",
  },

  // SEXUAL WELLNESS - DEUS
  {
    id: "sexual-deus-001",
    name: "DEUS CIAMED 5",
    description: "Tadalafil 5mg",
    price: 20.0,
    image: "/products/deus sexual wellness/DEUS CIAMED 5.png",
    category: "SEXUAL WELLNESS",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "sexual-deus-002",
    name: "DEUS PRILIMED 30",
    description: "Dapoxetine HCL 30mg",
    price: 15.0,
    image: "/products/deus sexual wellness/DEUS PRILIMED 30.png",
    category: "SEXUAL WELLNESS",
    brand: "deus",
    filterType: "Base",
  },
  {
    id: "sexual-deus-003",
    name: "DEUS VIAMED 20",
    description: "Sildenafil Citrate 20mg",
    price: 11.0,
    image: "/products/deus sexual wellness/DEUS VIAMED 20.png",
    category: "SEXUAL WELLNESS",
    brand: "deus",
    filterType: "Base",
  },

  // SEXUAL WELLNESS - ASTERA
  {
    id: "sexual-astera-001",
    name: "ASTERA DAPOXETINE 60",
    description: "Dapoxetine HCL 60mg",
    price: 30.0,
    image: "/products/astera sexual wellness/ASTERA DAPOXETINE 60.png",
    category: "SEXUAL WELLNESS",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "sexual-astera-002",
    name: "ASTERA SEX HARD & STRONG MIX 50:20:30",
    description: "Sildenafil Citrate 50mg, Tadalafil 20mg, Dapoxetine HCL 30mg",
    price: 90.0,
    image:
      "/products/astera sexual wellness/ASTERA SEX HARD & STRONG MIX 50:20:30.png",
    category: "SEXUAL WELLNESS",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "sexual-astera-003",
    name: "ASTERA SEX HARD MIX 50:20",
    description: "Sildenafil Citrate 50mg, Tadalafil 20mg",
    price: 70.0,
    image: "/products/astera sexual wellness/ASTERA SEX HARD MIX 50:20.png",
    category: "SEXUAL WELLNESS",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "sexual-astera-004",
    name: "ASTERA SILDENAFIL CITRATE 100 XL",
    description: "Sildenafil Citrate 100mg",
    price: 70.0,
    image:
      "/products/astera sexual wellness/ASTERA SILDENAFIL CITRATE 100 XL.png",
    category: "SEXUAL WELLNESS",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "sexual-astera-005",
    name: "ASTERA SILDENAFIL CITRATE 100",
    description: "Sildenafil Citrate 100mg",
    price: 40.0,
    image: "/products/astera sexual wellness/ASTERA SILDENAFIL CITRATE 100.png",
    category: "SEXUAL WELLNESS",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "sexual-astera-006",
    name: "ASTERA TADALAFIL 20 XL",
    description: "Tadalafil 20mg",
    price: 72.0,
    image: "/products/astera sexual wellness/ASTERA TADALAFIL 20 XL.png",
    category: "SEXUAL WELLNESS",
    brand: "astera",
    filterType: "Base",
  },
  {
    id: "sexual-astera-007",
    name: "ASTERA TADALAFIL 20",
    description: "Tadalafil 20mg",
    price: 40.0,
    image: "/products/astera sexual wellness/ASTERA TADALAFIL 20.png",
    category: "SEXUAL WELLNESS",
    brand: "astera",
    filterType: "Base",
  },

  // AMINO ACIDS - DEUS
  // Placeholder for future DEUS amino acid products

  // AMINO ACIDS - ASTERA
  // Placeholder for future ASTERA amino acid products
];

// Helper function to get filtered products
export const getFilteredProducts = (
  category: CategoryLabel,
  brand: Brand | null,
  filterType: string,
  sortBy: string,
) => {
  let filtered = products;

  if (category !== "ALL PRODUCTS") {
    filtered = filtered.filter((product) => product.category === category);
  }

  // Only filter by brand if a specific brand is selected (not null for ALL BRANDS)
  if (brand !== null && brand !== undefined) {
    filtered = filtered.filter((product) => product.brand === brand);
  }

  if (filterType) {
    filtered = filtered.filter((product) => product.filterType === filterType);
  }

  // Extract active substance name from description (remove dosage)
  // e.g. "Boldenone Undecylenate 250mg" -> "Boldenone Undecylenate"
  const getActiveSubstance = (description: string): string => {
    // Remove dosage numbers and units at the end (e.g., " 250mg", " 100", " 50mg")
    return description.replace(/\s+[\d.]+\s*(mg|ml|mcg)?$/i, "").trim();
  };

  // Sort products
  filtered.sort((a, b) => {
    switch (sortBy) {
      case "price-low":
        return a.price - b.price;
      case "price-high":
        return b.price - a.price;
      case "name":
      default:
        // Sort by active substance alphabetically
        const substanceA = getActiveSubstance(a.description);
        const substanceB = getActiveSubstance(b.description);
        return substanceA.localeCompare(substanceB);
    }
  });

  return filtered;
};

// Helper function to get unique filter types for a category
export const getAvailableFilters = (category: CategoryLabel) => {
  let categoryProducts = products;
  if (category !== "ALL PRODUCTS") {
    categoryProducts = products.filter(
      (product) => product.category === category,
    );
  }
  const filters = [
    ...new Set(categoryProducts.map((p) => p.filterType).filter(Boolean)),
  ];
  return filters;
};
